spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:authsecuritydemo}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


